### PR TITLE
batch_dim explicitly passed

### LINKED ISSUE #1121: Random_normal during forward: must feed size tensor
I am currently working on random sampling and while training with a config worked flawlessly, using the config for inference causes problems. I assume this is only happening because during training I am using `declare_same_as` for a loss, but this does not work for forward since I am doing upsampling with lengths the model predicts, so there will be a mismatch if I just put `declare_same_as`  (Error goes away but a different shape mismatch error occurs). But this only for context, now to the problem.

```
TensorFlow exception: 2 root error(s) found.
  (0) Invalid argument: You must feed a value for placeholder tensor 'extern_data/placeholders/audio_features/audio_features_dim0_size' with dtype int32 and shape [?]
         [[node extern_data/placeholders/audio_features/audio_features_dim0_size (defined at u/hilmes/returnn/returnn/tf/util/data.py:5651) ]]
         [[random/random/stateful_normal/_17]]
  (1) Invalid argument: You must feed a value for placeholder tensor 'extern_data/placeholders/audio_features/audio_features_dim0_size' with dtype int32 and shape [?]
         [[node extern_data/placeholders/audio_features/audio_features_dim0_size (defined at u/hilmes/returnn/returnn/tf/util/data.py:5651) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'extern_data/placeholders/audio_features/audio_features_dim0_size':
  File "u/hilmes/returnn/rnn.py", line 11, in <module>
    main()
  File "u/hilmes/returnn/returnn/__main__.py", line 657, in main
    execute_main_task()
  File "u/hilmes/returnn/returnn/__main__.py", line 489, in execute_main_task
    engine.init_network_from_config(config)
  File "u/hilmes/returnn/returnn/tf/engine.py", line 1121, in init_network_from_config
    self._init_network(net_desc=net_dict, epoch=self.epoch)
  File "u/hilmes/returnn/returnn/tf/engine.py", line 1297, in _init_network
    extern_data.init_from_config(config=self.config, auto_create_placeholders=not use_dataset_pipeline)
  File "u/hilmes/returnn/returnn/tf/network.py", line 68, in init_from_config
    self.data[key] = Data(name=key, auto_create_placeholders=auto_create_placeholders, **init_args)
  File "u/hilmes/returnn/returnn/tf/util/data.py", line 2733, in __init__
    _auto_create_size_placeholders_on_dim_tags(name=name, dim_tags=dim_tags)
  File "u/hilmes/returnn/returnn/tf/util/data.py", line 5790, in _auto_create_size_placeholders_on_dim_tags
    _create_size_placeholder(name=name, axis_wo_b=axis_wo_b, tag=tag, batch_dim=batch_dim_)
  File "u/hilmes/returnn/returnn/tf/util/data.py", line 5651, in _create_size_placeholder
    dyn_size = tf_compat.v1.placeholder(
  File "work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 3100, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/ops/gen_array_ops.py", line 6808, in placeholder
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 742, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3477, in _create_op_internal
    ret = Operation(
  File "work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1949, in __init__
    self._traceback = tf_stack.extract_stack()

Exception InvalidArgumentError() in step 0. (pid 2438)
Failing op: <tf.Operation 'extern_data/placeholders/audio_features/audio_features_dim0_size' type=Placeholder>
Used by: [<tf.Operation 'extern_data/placeholders/audio_features/batch_dim/Shape' type=Shape>]
  File "/u/hilmes/returnn/rnn.py", line 11, in <module>
    main()                                                                                                                                                                        [201/1980]  File "/u/hilmes/returnn/returnn/__main__.py", line 657, in main
    execute_main_task()
  File "/u/hilmes/returnn/returnn/__main__.py", line 489, in execute_main_task
    engine.init_network_from_config(config)
  File "/u/hilmes/returnn/returnn/tf/engine.py", line 1121, in init_network_from_config
    self._init_network(net_desc=net_dict, epoch=self.epoch)
  File "/u/hilmes/returnn/returnn/tf/engine.py", line 1297, in _init_network
    extern_data.init_from_config(config=self.config, auto_create_placeholders=not use_dataset_pipeline)
  File "/u/hilmes/returnn/returnn/tf/network.py", line 79, in init_from_config
    self.init_batch_info()
  File "/u/hilmes/returnn/returnn/tf/network.py", line 159, in init_batch_info
    batch_dim = get_shape_dim(data.size_placeholder[0], 0, name="batch_dim")
  File "/u/hilmes/returnn/returnn/tf/util/basic.py", line 879, in get_shape_dim
    return tf.shape(x)[axis]
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 601, in shape_v2
    return shape(input, name, out_type)
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 628, in shape
    return shape_internal(input, name, optimize=True, out_type=out_type)
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 656, in shape_internal
    return gen_array_ops.shape(input, name=name, out_type=out_type)
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/ops/gen_array_ops.py", line 9035, in shape
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 742, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3477, in _create_op_internal
    ret = Operation(
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1949, in __init__
    self._traceback = tf_stack.extract_stack()

Input to output:
[<tf.Operation 'extern_data/placeholders/audio_features/audio_features_dim0_size' type=Placeholder>,
 <tf.Operation 'extern_data/placeholders/audio_features/batch_dim/Shape' type=Shape>,
 <tf.Operation 'extern_data/placeholders/audio_features/batch_dim/strided_slice' type=StridedSlice>,
 <tf.Operation 'random/random/stateful_normal/shape' type=Pack>,
 <tf.Operation 'random/random/stateful_normal/StatefulStandardNormalV2' type=StatefulStandardNormalV2>,
 <tf.Operation 'random/random/stateful_normal/mul' type=Mul>,
 <tf.Operation 'random/random/stateful_normal' type=Add>]
Step meta information:
{'seq_idx': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
 'seq_tag': ['train-clean-100/7859-102521-0000/7859-102521-0000',
             'train-clean-100/3259-158083-0039/3259-158083-0039',
             'train-clean-100/1183-128659-0018/1183-128659-0018',
             'train-clean-100/8063-274117-0028/8063-274117-0028',
             'train-clean-100/7278-91083-0002/7278-91083-0002',
             'train-clean-100/2843-152918-0005/2843-152918-0005',
             'train-clean-100/1926-147979-0049/1926-147979-0049',
             'train-clean-100/4195-17507-0023/4195-17507-0023',
             'train-clean-100/1447-130550-0021/1447-130550-0021',
             'train-clean-100/4680-16042-0027/4680-16042-0027',
             'train-clean-100/5022-29411-0018/5022-29411-0018',
             'train-clean-100/2002-139469-0115/2002-139469-0115',
             'train-clean-100/3436-172162-0052/3436-172162-0052',
             'train-clean-100/8975-270782-0114/8975-270782-0114',
             'train-clean-100/3242-8112-0009/3242-8112-0009',
             'train-clean-100/1455-138263-0002/1455-138263-0002']}
Feed dict:
  <tf.Tensor 'extern_data/placeholders/phonemes/phonemes:0' shape=(?, ?) dtype=int32>: shape (16, 51), dtype int32, min/max 0/42, Data{'phonemes', [B,T|'phonemes_time'[B]], dtype='int32', sparse_dim=Dim{F'phonemes_indices'(44)}}
  <tf.Tensor 'extern_data/placeholders/phonemes/phonemes_dim0_size:0' shape=(?,) dtype=int32>: shape (16,), dtype int32, min/max 18/51, ([18 24 27 26 39 34 32 41 29 35 38 27 46 46 51 40])
  <tf.Tensor 'extern_data/placeholders/seq_tag/seq_tag:0' shape=(?,) dtype=string>: type <class 'list'>, Data{'seq_tag', [B?], dtype='string'}
EXCEPTION
Traceback (most recent call last):
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1365, in BaseSession._do_call
    line: return fn(*args)
    locals:
      fn = <local> <function BaseSession._do_run.<locals>._run_fn at 0x7f9116435af0>
      args = <local> ({<tensorflow.python._pywrap_tf_session.TF_Output object at 0x7f915728cdf0>: array([[42, 41,  9,  2, 41,  5, 19,  2, 22,  2, 19, 20,  1, 28, 30, 28,
                             41, 40,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
                              0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
                         ...
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1349, in BaseSession._do_run.<locals>._run_fn
    line: return self._call_tf_sessionrun(options, feed_dict, fetch_list,
                                          target_list, run_metadata)
    locals:
      self = <local> <tensorflow.python.client.session.Session object at 0x7f9154d74b20>
      self._call_tf_sessionrun = <local> <bound method BaseSession._call_tf_sessionrun of <tensorflow.python.client.session.Session object at 0x7f9154d74b20>>
      options = <local> None
      feed_dict = <local> {<tensorflow.python._pywrap_tf_session.TF_Output object at 0x7f915728cdf0>: array([[42, 41,  9,  2, 41,  5, 19,  2, 22,  2, 19, 20,  1, 28, 30, 28,
                                  41, 40,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
                                   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
                               ...
      fetch_list = <local> [<tensorflow.python._pywrap_tf_session.TF_Output object at 0x7f91573a3b30>]
      target_list = <local> []
      run_metadata = <local> None
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1441, in BaseSession._call_tf_sessionrun
    line: return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
                                                  fetch_list, target_list,
                                                  run_metadata)
    locals:
      tf_session = <global> <module 'tensorflow.python.client.pywrap_tf_session' from '/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/client/pywrap_tf_session.py'>
      tf_session.TF_SessionRun_wrapper = <global> <built-in method TF_SessionRun_wrapper of PyCapsule object at 0x7f923b7c5cf0>
      self = <local> <tensorflow.python.client.session.Session object at 0x7f9154d74b20>
      self._session = <local> <tensorflow.python._pywrap_tf_session.TF_Session object at 0x7f91574c47b0>
      options = <local> None
      feed_dict = <local> {<tensorflow.python._pywrap_tf_session.TF_Output object at 0x7f915728cdf0>: array([[42, 41,  9,  2, 41,  5, 19,  2, 22,  2, 19, 20,  1, 28, 30, 28,
                                  41, 40,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
                                   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
                               ...
      fetch_list = <local> [<tensorflow.python._pywrap_tf_session.TF_Output object at 0x7f91573a3b30>]
      target_list = <local> []
      run_metadata = <local> None
InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: You must feed a value for placeholder tensor 'extern_data/placeholders/audio_features/audio_features_dim0_size' with dtype int32 and shape [?]
         [[{{node extern_data/placeholders/audio_features/audio_features_dim0_size}}]]
         [[random/random/stateful_normal/_17]]
  (1) Invalid argument: You must feed a value for placeholder tensor 'extern_data/placeholders/audio_features/audio_features_dim0_size' with dtype int32 and shape [?]
         [[{{node extern_data/placeholders/audio_features/audio_features_dim0_size}}]]
0 successful operations.
0 derived errors ignored.
```

Then there is a similar exception below which ends with: 
```
InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: You must feed a value for placeholder tensor 'extern_data/placeholders/audio_features/audio_features_dim0_size' with dtype int32 and shape [?]
         [[node extern_data/placeholders/audio_features/audio_features_dim0_size (defined at u/hilmes/returnn/returnn/tf/util/data.py:5651) ]]
         [[random/random/stateful_normal/_17]]
  (1) Invalid argument: You must feed a value for placeholder tensor 'extern_data/placeholders/audio_features/audio_features_dim0_size' with dtype int32 and shape [?]
         [[node extern_data/placeholders/audio_features/audio_features_dim0_size (defined at u/hilmes/returnn/returnn/tf/util/data.py:5651) ]]
0 successful operations.
0 derived errors ignored.
```

I was able to shrink down the network and the confusing part is: Even when removing the part that relies on the size tensor (e.g. upsampling etc.) the error persists as long as `nn.random_normal` is in the network.
The smallest net I was able to reproduce the error with was:
```
class NARTTSModel(nn.Module):
  def __init__(self):
    super(NARTTSModel, self).__init__()
    vae_lin_dim = nn.FeatureDim("vae_embedding", 512)
    self.vae_embedding = nn.Linear(vae_lin_dim)

  def __call__(self, text: nn.Tensor):
    vae_embedding = self.vae_embedding(text)
    rand = nn.random_normal(vae_embedding.shape_ordered)
    return rand
```
When removing the `random_normal` part this works.

A gist with the shrinked returnn config is here: [returnn.config](https://gist.github.com/Atticus1806/5cc9ff3e7bc32666af2be34e025e7d9d)

### PR DESCRIPTION
**Pull request by albertz**
Fix #1121

### CODE REVIEW

**Comment by albertz** [comment]
Likely a number of tests are now broken, which handcraft the feed dict.
Maybe also some external code. I'm not sure. @patrick-wilken maybe?

**Comment by patrick-wilken** [comment]
If I understand the code correctly feeding "batch_dim" is only required if it can't be inferred from the data, right?
So a manually created feed dicts may be different from the output of `get_feed_dict()` now, but should still work as long as the "batch_dim" placeholder is unused, right?

**Comment by albertz** [comment]
> If I understand the code correctly feeding "batch_dim" is only required if it can't be inferred from the data, right?

No, I completely changed it. It is not inferred automatically anymore, as this was buggy (see https://github.com/rwth-i6/returnn/issues/1121). It always needs to be fed explicitly.

> but should still work as long as the "batch_dim" placeholder is unused

When it is unused, it would not matter. However, it is used in quite a lot of places. E.g. also for things like beam search, creating initial state vector, etc.

**Comment by albertz** [comment]
> So then any TF graph created with RETURNN has now a mandatory "batch_dim" input? If yes, of course this breaks a lot of stuff.

Yes, exactly.

> Any setup that exports models as graphs, or not? And any custom inference implementation that does not use `get_feed_dict()`.

Yes.

**Comment by albertz** [comment]
Regarding TF graphs: @curufinwe @ZijYang @ZhouW321 this needs some extra logic for RASR.

**Comment by albertz** [comment]
Actually, I think we can make it backward compatible, by keeping the old code in place, but still also feeding it explicitly.

**Comment by albertz** [comment]
See https://github.com/rwth-i6/returnn/pull/1123.

**Pull request merged**
