### PR TITLE
add test_CombineLayer_feature_broadcast_swapped

### PR DESCRIPTION
**Pull request by vieting**
Added test case for #719

### CODE REVIEW

**Comment by vieting** [comment]
I accidentally force pushed here, didn't know this branch was still used for a PR. I'm closing this due to inactivity.

**Comment by albertz** [comment]
You did not add much details to the corresponding issue in #719. Is this still an issue? If so, it would be good if you could add the test case directly there.

**Comment by vieting** [comment]
> You did not add this test case to the corresponding issue in #719. It would be good if you could add the test case directly there.

Done.

**Comment by vieting** [comment]
Can I somehow unlink the branch from this PR? Otherwise I will always push changes to this PR if I use a branch `dev` on my fork.

**Pull request closed without merging**
