### PR TITLE
get_seq_order_for_epoch: fix seq_tags_filter

### PR DESCRIPTION
**Pull request by patrick-wilken**
@sarahberanek Can you try? Should be all that is needed to get seq_tags_filter working again.

### CODE REVIEW

**Review by JackTemaki — CHANGES_REQUESTED** [review]
Doesn't line 490 need a change as well?

**Comment by patrick-wilken** [comment]
Not necessarily, there it is definitively a list. The problem was that `assert seq_index` does not work for numpy arrays.

(I changed `seq_index` to a generic `typing.Sequence` for efficiency: numpy sorting and random permutations are much faster, and for "default" sequence order we can just use a range, which uses up no memory.)

**Review by albertz — APPROVED** [review]

**Comment by albertz** [comment]
So we wait for @sarahberanek ? Otherwise looks fine.

**Review by JackTemaki — APPROVED** [review]

**Comment by sarahberanek** [comment]
Hi all, I just tried it and this seems to fix the issue: Training starts smoothly. Thanks everyone!

**Pull request merged**
