### PR TITLE
CopyLayer: always get out_type from sources if possible

### PR DESCRIPTION
**Pull request by patrick-wilken**
`get_concat_sources_data_template` should be the right thing to do in all cases to create the output template.

Logic depending on `n_out` can lead to problems, e.g.:
`n_out` is set via `LayerBase.transform_config_dict()` if a layer has a target. Using super(CopyLayer, cls).get_out_data_from_opts in this case fails to set `sparse=True`.

Should we add a check that, if `out_type` or `n_out` are given, they match the result of  `get_concat_sources_data_template`?

### CODE REVIEW

**Comment by albertz** [comment]
Yes, at least for `n_out` there should be a check, maybe also for `out_type`.

**Comment by albertz** [comment]
Tests are failing.

**Comment by patrick-wilken** [comment]
Hmm, ok, I will look into it.

**Comment by patrick-wilken** [comment]
Ok, the test was failing in a case where the copy layer was the only layer in the net and the only input was an "initial_output". Here we need the `out_type`. All layers ignoring `out_type` would fail under this condition (and there are quite a few).

So now I simply changed the order: first try to get the shape from the sources (which always works if they are defined) and only if necessary resort to the out_type. This solves my problem with `sparse` not being set and also passes the test.

**Pull request merged**
