### PR TITLE
Tests for self attention using CumConcatLayer

### PR DESCRIPTION
**Pull request by Zettelkasten**
Some tests for #391.
I didn't run any of this yet (so most likely buggy) because there is no implementation.
It still needs `CumConcatLayer` from #589, but also the `common` arguments for `DotLayer` from #569.
Also, some way to set dim tags (e.g. `set_dim_tags: Dict[str, DimensionTag]` for `ReinterpretDataLayer`. I'm not sure, didn't we add this already somewhere?)

We might also want more tests than this: e.g. some with positional encoding.

### CODE REVIEW

**Comment by Zettelkasten** [comment]
This should be ready now.

I left in `test_self_attention_optimize_out`, which essentially does the same as `test_reclayer_optimize_out_cum_concat_gen_self_att`. Should we remove that?

**Comment by albertz** [comment]
There is also `test_generalized_non_rec_self_attention` already now.

I did not check in detail, is this really exactly the same, or just similar? What is the difference?
If there is some difference which makes sense for another test, then leave it. Otherwise remove it.

**Comment by Zettelkasten** [comment]
> There is also `test_generalized_non_rec_self_attention` already now.

Oh okay, I missed that.

The test case in this PR also checks that `SelfAttentionLayer` does the same as the generalized self attention for the recurrent case (not just non-rec). Maybe we want to check that too.
But maybe we can just close this PR, it's a lot new code which originally was meant to be much more general. I think the test cases we already have are nicer because they use an explicit net dict and seem easier to debug if something goes wrong.

**Comment by albertz** [comment]
Hm, I don't know. It might be nice as an example. I would say leave it.

**Review by albertz — APPROVED** [review]

**Pull request merged**
