### PR TITLE
Direct support for flattened/packed arrays

### PR DESCRIPTION
**Pull request by albertz**
This partly implements #466.

### CODE REVIEW

**Comment by albertz** [comment]
These (and related) changes will probably get big. So maybe we should split this PR up?

So far this contains just the basic extensions for `Data`, as proposed. It's somewhat incomplete, but it's done in a way not to break existing code/configs. This is probably not so debatable anyway. So maybe we can merge this already, and then improve further with other separate PRs.

**Comment by albertz** [comment]
(It's enough if at least one of you reviews. This will only be the base for future changes anyway.)

**Comment by albertz** [comment]
As no-one has commented yet, and I already restructured some parts of `BatchInfo`, I directly pushed this to this PR.

**Review by Zettelkasten — COMMENTED** [review]
This looks good I think! I did not spot anything that seems off.

**Pull request merged**
