### PR TITLE
Layer output, always set batch info

### PR DESCRIPTION
**Pull request by albertz**
This came up via https://github.com/rwth-i6/returnn_common/issues/199.

### CODE REVIEW

**Comment by albertz** [comment]
@JackTemaki This was important to fix the problem in https://github.com/rwth-i6/returnn_common/issues/199 because the output of the RecLayer had shape [k_dim], i.e. it did not had a batch dim, and thus `Data._adapt_batch_consistent_dim_tags` did not had an effect (due to its current implementation), and thus the dim tag of that output was not correctly adapted. This was easy to see in the debugger.

**Comment by JackTemaki** [comment]
> @JackTemaki This was important to fix the problem in [rwth-i6/returnn_common#199](https://github.com/rwth-i6/returnn_common/issues/199) because the output of the RecLayer had shape [k_dim], i.e. it did not had a batch dim, and thus `Data._adapt_batch_consistent_dim_tags` did not had an effect (due to its current implementation), and thus the dim tag of that output was not correctly adapted. This was easy to see in the debugger.

What does `not correctly adapted` mean in this sense?

**Comment by albertz** [comment]
> What does "not correctly adapted" mean in this sense?

What `Data._adapt_batch_consistent_dim_tags` does, i.e. switching to the right dim tag instance, via `Dim.get_for_batch_ctx`.

Note that #975 is somewhat related to this.

**Comment by JackTemaki** [comment]
> > What does "not correctly adapted" mean in this sense?
> 
> What `Data._adapt_batch_consistent_dim_tags` does, i.e. switching to the right dim tag instance, via `Dim.get_for_batch_ctx`.
> 
> Note that #975 is somewhat related to this.

Hmm yes this function is hard to read. I also played around with the debugger, so I see `dyn_size` for the `k_dim` Dim is set correctly and then at some point suddenly not, but I would have no idea how to actually find from there the location where it is suddenly changed.

**Comment by albertz** [comment]
> I also played around with the debugger, so I see `dyn_size` for the `k_dim` Dim is set correctly and then at some point suddenly not, but I would have no idea how to actually find from there the location where it is suddenly changed.

The point where it is not correctly set, this is a different layer (`RecLayer`, not `TopKLayer`), different layer output `Data`, and then a different instance of `Dim`, relating to the same `k_dim` (see `same_as` logic, `get_for_batch_ctx`).

**Pull request merged**
