### PR TITLE
MultiEpochDataset: implement get_current_seq_order

### PR DESCRIPTION
**Pull request by dorian-K**

### CODE REVIEW

**Comment by dorian-K** [comment]
I just realized this patch is wrong, it only works correctly when multi_epoch=1

**Review by albertz — CHANGES_REQUESTED** [review]
But this is wrong. The sub dataset does not have the same seq order but only a subset. The MultiEpochDataset will go over multiple epochs in the sub dataset.

**Comment by albertz** [comment]
> I just realized this patch is wrong, it only works correctly when multi_epoch=1

Yes exactly.

I don't think there is an easy way (or any way at all in general) to implement `get_current_seq_order`. So I think we can only close this PR without having this implemented.

Btw, why do you need this?

**Comment by dorian-K** [comment]
MetaDataset needs this method when setting a MultiEpochDataset as the `seq_order_control_dataset`.

**Comment by albertz** [comment]
> MetaDataset needs this method when setting a MultiEpochDataset as the `seq_order_control_dataset`.

Yea, don't do that. :)

**Pull request closed without merging**
