### PR TITLE
Fixed SliceLayer

### PR DESCRIPTION
**Pull request by ChristopherBrix**
This should fix the behavior of the `SliceLayer`, resolving issue #206 

Because shorter sequences have some padding, we cannot rely on the shape of the `placeholder` to determine the new `size_placeholder`. Also, we should ignore the padding when using negative indexing.

This PR should probably also contain some new test cases, that demonstrate where the old code was wrong. So far, I've only checked by hand. I can add tests later.

### CODE REVIEW

**Comment by ChristopherBrix** [comment]
I just noticed I'm not using `size_placeholder` correctly (it's a dict, I'm using it as a tensor). As it is, the could will fail on execution.

Shouldn't be complicated to fix, but I don't have the time just yet. I'll fix this tomorrow.

**Comment by ChristopherBrix** [comment]
I need to use a negative end index to remove the last token. Just fixing the size_placeholder wasn't enough, as the actual selection would still be wrong (for an input sequence of length 4 with 2 padding, the output would still have length 4 but a size_placeholder saying it has length 3). This might be ok if a later layers respect the size_placeholder, but still may cause confusion.
A quick fix would have been to apply masking after the selection, but this would not support negative slice steps (which I don't need right now).

I can change it to this simpler approach, if you don't thing the full functionality is required.

**Comment by albertz** [comment]
The size_placeholder is always respected (if not, that would be a separate bug; and as you say, maybe you can have an explicit TimeMaskingLayer or so to work around this). There can be any data in the padding area. This is totally fine. There are multiple other layers which also leave arbitrary data in there. This is expected.

**Comment by albertz** [comment]
Ping?

**Comment by ChristopherBrix** [comment]
I've reversed my change, and implemented the simpler variant. Now, start and step size must be non-negative and positive, respectively.

**Comment by albertz** [comment]
In the meanwhile, I also fixed it (in a simple way) in 7e912cc36a9bf, which I will soon merge in. So I guess this becomes obsolete now. Looks very similar though.

**Comment by ChristopherBrix** [comment]
Yes, we did it similarly.
In your code, when is 

```
tf.minimum(
  tf.shape(self.input_data.placeholder)[axis] + slice_end,
  self.output.size_placeholder[axis_wo_batch] + slice_end)
```

needed? This should always equal `self.output.size_placeholder[axis_wo_batch] + slice_end)`, or otherwise the `size_placeholder` specified a sequence length longer than the actual `placeholder`. I guess this would be a separate bug?

**Comment by albertz** [comment]
Ah yes I think you are right.

**Comment by albertz** [comment]
Ok, this is now in de2bcfc.
I guess we can close this now. Please open a new pull request if you need anything else.

**Pull request closed without merging**
