### PR TITLE
Use -std=c++11 for GCC 5 and lower

### PR DESCRIPTION
**Pull request by albertz**
Updated PR #875, resolving the concerns, and also fixing #890.

### CODE REVIEW

**Comment by JackTemaki** [comment]
I tried and still got `c++14` in the compile command, I will debug this now.

**Comment by JackTemaki** [comment]
Ah right, I was not so smart... This works of course for our custom compiled Tensorflow versions, but not for pip installed ones, as there the GCC version is 7.3.1, so not reflecting the actual GCC version that can be found.

Well, for me this would be good enough.

**Comment by albertz** [comment]
> Ah right, I was not so smart... This works of course for our custom compiled Tensorflow versions, but not for pip installed ones, as there the GCC version is 7.3.1, so not reflecting the actual GCC version that can be found.
> 
> Well, for me this would be good enough.

Yes it just looks at the `tf.__compiler_version__` currently.

But this should work in your case when you use your custom compiled TF (compiled with GCC 5) (using `-std=c++11`).

When you use the pip package (compiled with GCC 7), and you have GCC 7 (or newer) available, it should also be correct (using `-std=c++14`).

When you use the pip package and you do not have a matching GCC version installed, it would anyway not work.

**Comment by albertz** [comment]
@JackTemaki You did not respond anymore. I assume everything is fine? So I merge now.

**Comment by albertz** [comment]
Small follow-up in commit 72cc8d15f72caefd55bb5eb87eaf4a629dfee09f.

**Comment by JackTemaki** [comment]
> @JackTemaki You did not respond anymore. I assume everything is fine? So I merge now.

I could not validate yet the "it would anyway not work" statement, because I am sure this worked in some cases. But we can just leave it like it is until someone complains.

**Pull request merged**
