### PR TITLE
axis description for any tag

### PR DESCRIPTION
**Pull request by vieting**
It is already possible to use axis descriptions for spatial tags like `"axis": "stag:<...>"`. I'd like to add that functionality for static dims as well, e.g. via `"axis": "tag:<...>"` for any tag.

### CODE REVIEW

**Comment by albertz** [comment]
Why do you need this?

I think it was already discussed somewhere else that even `stag:...` is deprecated and we do not want to encourage more use of that and extend that.

The problem is that the description of a dim tag is ambiguous and also we do not guarantee that it will not change, and thus any config using this might break at some future point.

The reliable way is to just use the dim tag object directly.

**Comment by vieting** [comment]
It would simplify an issue that I have with the pytorch-to-returnn converter a lot. I admit it is not the cleanest way possible, though. Should I open an issue for the converter with that case?

**Comment by vieting** [comment]
Sounds good to me. Should I add a comment that it is not recommended to use that option as it might change behavior in the future?

**Review by albertz — APPROVED** [review]
Ok for now.

**Pull request merged**
