### PR TITLE
SelfAttentionLayer: add global inf_value option

### PR DESCRIPTION
**Pull request by Gerstenberger**
Add global config option "inf_value" to the SelfAttentionLayer.
We need this to convert acoustic models to ONNX. The current value results in nan values.

### CODE REVIEW

**Comment by Gerstenberger** [comment]
> Looks good. Can you search for other places of `inf` in RETURNN? Those other places probably should also use this. E.g. `SoftmaxOverSpatialLayer`.

Sure, i can do that.

**Comment by albertz** [comment]
Also `SeqLenMaskLayer`, `DotAttentionLayer`, `ConcatAttentionLayer`.

**Comment by albertz** [comment]
And `softmax_cross_entropy_over_size`.

**Comment by albertz** [comment]
As far as I can see, those are the relevant uses.

**Comment by albertz** [comment]
`SeqLenMaskLayer` missing?

**Comment by Gerstenberger** [comment]
I adapted `SoftmaxOverSpatialLayer`, `DotAttentionLayer`, `ConcatAttentionLayer` and `softmax_cross_entropy_over_size`.

`SeqLenMaskLayer` looks okay to me as is. The only inf values i can find is the check for `self.allow_inf_in_output`.

**Review by albertz — APPROVED** [review]

**Pull request merged**
