### PR TITLE
Bug fixed in SliceLayer. Didn't work in the NCHW mode.

### PR DESCRIPTION
**Pull request by squarenabla**

### CODE REVIEW

**Comment by albertz** [comment]
Please check the tests. Some of them fail (e.g. [here](https://travis-ci.org/rwth-i6/returnn/jobs/466971643)).
Also, please use standard conventions for the Git commit message (read a Git tutorial if unsure). I.e. it should not be a sentence in the description (first line), but just a short description (no dot at the end). Then most importantly it should be clear of what class and/or function you changed something. This is not clear at all from your commit message. It should be like `SliceLayer: ...`. Also, your message is kind of wrong. It's not really about NCHW. It's for any case where you specify a custom `feature_dim_axis`. So the message should be like `SliceLayer: fix for custom feature_dim_axis`.

**Comment by albertz** [comment]
What is the state here?

**Comment by albertz** [comment]
What is the state here? Please respond to my comment.

**Comment by albertz** [comment]
What is the state here?

**Comment by squarenabla** [comment]
Sorry, didn't notice the message. I cleaned the code and made one pull request for all minor fixes in TFNetworkLayer

**Comment by squarenabla** [comment]
Closing the pull request

**Pull request closed without merging**
