### PR TITLE
removed empty tokens when there are [XXX] in the sentence 

### PR DESCRIPTION
**Pull request by jiangj-apptek**

### CODE REVIEW

**Comment by albertz** [comment]
Why did you open a new PR? Don't do that.

Also, do not push multiple commits. Make this a single commit.

**Comment by jiangj-apptek** [comment]
yes, the same issue. what to do with #431 then?

**Comment by albertz** [comment]
> yes, the same issue. what to do with #431 then?

I don't quite understand. We only need one PR, not two. (So now that you incorrectly created two, close one of them.)
In the future, do not create multiple PRs. Just update the PR instead.

**Comment by jiangj-apptek** [comment]
Anything to do at this time?

**Comment by albertz** [comment]
> Anything to do at this time?

Yes, as I explained:

* Close all but the original PR
* Update the original PR
* Cleanup the commits (make it a single commit)

**Pull request closed without merging**
